### ISSUE TITLE
Drop Box 

### ISSUE THREAD

**Issue by CCradio1** [edgeradio993fm/rivendell#1]
Hello 
First thank you for this great resource! .. I'm just getting my feet wet with Rivendell I'm running it on a Pi4 with a HIFI Berry hat seems to work well.. I have one perplexing issue I cant solve.. When using A drobox I setup the filter the song is imported but it seems to ignore the Segue Level field all together.. I originally installed 3.2 I'm now running 3.5 of Rivendell and the behavior is the same.. When I check the file in RD library they always look the same Segue end is 4 seconds before segue begin and the times are always the end of file times.. Thank You

**Comment by alastairtech** [comment]
Hi @CCradio1. Thanks for giving Rivendell on ARM a spin. Hopefully everything else is working as it should. I'll look into the dropbox segue issue. Personally I've always found Dropboxes to be a bit hit and miss on overall functionality on both desktop and ARM devices. 

You might want to test a command line import just using the **rdimport** function. I'll put an example below. I've written it assuming that you have a folder in your home directory called Music. Keep in mind everything in Linux is case sensitive. So what you do is place some audio files in that folder, open up a terminal and run the below command. It will import the audio files into the MUSIC category, trim them and add a segue at -15db. Fix Broken Formats is just to force any difficult files through.

```bash
rdimport --autotrim-level=-40 --segue-level=-15 --fix-broken-formats MUSIC "/home/pi/Music/*"
```

You might want to fiddle with the numbers to get a result you're happy with. Dropboxes are just a frontend to use the rdimport command. So if this works I can show you how to set up a persistent dropbox using a terminal command. I've also attached a PDF with all the rdimport commands with explanations.

[rdimport.pdf](https://github.com/edgeradio993fm/rivendell/files/6007187/rdimport.pdf)

**Comment by CCradio1** [comment]
Thank You so much for the response.. I modified your example and now I have the same basic functionality as the drop box plus working segue markers!!
The other interesting note is when I run the command line it works but I get this error message
pi@raspberrypi:~ $ rdimport --autotrim-level=-40 --segue-level=-15 --metadata-pattern=%a-%t --delete-source --fix-broken-formats MUSIC "/home/pi/MusicImport/*"
DB connection re-established
invalid SQL or failed DB connection[Out of range value for column 'MINIMUM_TALK_LENGTH' at row 1 QMYSQL: Unable to execute query]: update CART set MINIMUM_TALK_LENGTH=-1 where NUMBER=10001
Is this anything to worry about?

I would love to know how to setup a persistent drop box with these settings that would be perfect..  

Thanks again for the help!

**Comment by alastairtech** [comment]
Excellent. Seems the rdimport function is working correctly them. I've seen the error a number of times in the past. I think it's a depreciated database function that's being called. Nothing to worry about.

Anyway, persistent dropboxes aren't too hard using the rdimport command. You may have noticed a --drop-box switch option in the rdimport documentation. I've put an example below using it.

```bash
rdimport --autotrim-level=-40 --segue-level=-15 --metadata-pattern=%a-%t --drop-box --fix-broken-formats MUSIC "/home/pi/MusicImport/*"
```
The command will tell the Rivendell services to keep an eye on that folder and periodically import anything it sees. I'm pretty sure this doesn't create any entry in the rdadmin host settings. We'll see if this works for you and then I'll show you how to run the command as a background script at start up as it'll cease to function if you restart your Pi.

**Comment by CCradio1** [comment]
Things are moving along well I now have three rdimport drop boxes working well.. One for Music One for Liners and One for Spots..  I'm running them in 3 separate terminal windows but I'm guessing that's the only way to do that.. I have looked at ways to start them at startup and there seems to be multiple ways to get that done.. I cant seem to find a way to do that and run them hidden or in the background.. i look forward to your suggestions.. Thanks for the help. I look forward to the next steps

**Comment by alastairtech** [comment]
Apologies for the slow reply. I've only just had a chance to look at things this week. You can very easily run a dropbox as a background process by adding a **&** at the end of your **rdimport** command. The & symbol at the end tells the terminal to send the command to a background process and move to the next one. In this case there is no next command. It will output a number, that should be your process id. Here's an example.

```bash
rdimport --autotrim-level=-40 --segue-level=-15 --metadata-pattern=%a-%t --drop-box --fix-broken-formats MUSIC "/home/pi/MusicImport/*" &
```
I've been testing having them auto start at boot. Not luck yet. There are a number of ways to go about doing this. Just need to pick the more sensible one. But you can close your terminal windows once you've run the commands now.

**Comment by alastairtech** [comment]
Hopefully you got things sorted. I'm going to close this issue since it's been a few months now.
